### ISSUE TITLE
Build fails on ubuntu linux

### ISSUE THREAD

**Issue by algautschy** [rjfarmer/pyMesa#3]
My build process on mesa version 11701 failed at:

MAKEDEPF90
FC ../src/eos_correction.f
LDFLAGS = -Wl,-rpath=make:../lib
make: LDFLAGS: Command not found
makefile_base:69: recipe for target 'eos_correction.o' failed
make: *** [eos_correction.o] Error 127

/home/alfred/StarWare/Mesa/mesa/sample
FAILED

****************************************************************
pyMESA building fail
****************************************************************

Versions in use:
GNU Fortran (GCC) 8.3.0
gfort2py: 1.1.3
pyMesa: 1.0.3

Is there any quick fix for that?

Thanks and regards, 
Alfred

**Comment by rjfarmer** [comment]
There's no quick fix for now. But am looking into it

**Comment by rjfarmer** [comment]
Should be fixed now in mesa version 11731
