### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by Quacken8** [rjfarmer/pyMesa#6]
pyMESA build fails using the ./mesa-build.sh

```
************************************************
************************************************
************************************************

MESA installation was successful

************************************************
************************************************
************************************************


****************************************************************
pyMESA building fail
****************************************************************
```
becuase $MESA_DIR/lib contains only .a libraries, not shared .so libraries. I tried creating the .so from .a, but couldn't. Probably becuase the objects in the libraries weren't complied with the -fPIC tag. I'm not sure, I'm not experienced with fortran...

Is there some quick way around this? Can I provide any further information?

Used versions:
MESA version r22.11.1
pyMESA 1.0.3
gfortran 12.1.0

**Comment by rjfarmer** [comment]
The install instructions are out of date for newer mesa versions.  

Goto your $MESA_DIR/utils/makefile_header and find the flag use_shaerd and set that to YES 

Then do a ./clean and ./install in $MESA_DIR. That is then all you need to "install" pymesa.

**Comment by Quacken8** [comment]
Yes, that worked. Maybe the pyMESA mesa-build.sh could first look into makefile_header and make sure it's turned on before it installs MESA?
