### ISSUE TITLE
Access to Zbase in kappa module

### ISSUE THREAD

**Issue by Quacken8** [rjfarmer/pyMesa#7]
When trying to get opacities of type 2 it is required that I specify the Zbase variable, 
```
must supply Zbase for Type2 opacities   -1.0000000000000000D+00
File: ../private/kap_eval.f90, Line:  525
ERROR STOP 1
```
but in fortran that is always accessed via a pointer, for instance [here](https://github.com/MESAHub/mesa/blob/6b4527bb91bbd752182cb12e561e8c068e32b282/kap/test/src/sample_kap.f90#L22)
```
      program sample_kap
      use kap_lib
      use kap_def
      ...
      implicit none
      ...
      type (Kap_General_Info), pointer :: rq1, rq2
      ...
      call kap_ptr(handle1, rq1, ierr)
      ...
      rq1% Zbase = Z_init
      ...
```
Is there a way to resolve this and access Zbase from pyMesa?

**Comment by rjfarmer** [comment]
As zbase is a namelist input you can use

https://github.com/MESAHub/mesa/blob/6b4527bb91bbd752182cb12e561e8c068e32b282/kap/public/kap_lib.f90#L687

and

https://github.com/MESAHub/mesa/blob/6b4527bb91bbd752182cb12e561e8c068e32b282/kap/public/kap_lib.f90#L702

to get and set namelist variables.

**Comment by Quacken8** [comment]
Amazing, thank you for your quick and kind help
